name: worldsaver
version: '${project.version}'
main: me.freezy.plugins.worldsaver.worldsaver.Worldsaver
api-version: '1.20'
load: STARTUP
commands:
  saveworld:
    usage: /saveworld <name>
    aliases: [ worldsave ]
  loadworld:
    usage: /loadworld <name>
    aliases: [ worldload ]
  deleteworld:
    usage: /deleteworld <name>
    aliases: [ delworld, worlddel, worlddelete ]