name: worldsaver
version: '${project.version}'
main: me.freezy.plugins.worldsaver.worldsaver.Worldsaver
api-version: '1.20'
load: STARTUP
permissions:
  wssaver.admin:
    description: Allows all cmds!
    default: op
  wssaver.use.savecmd:
    description: Allows specific cmds!
    default: false
  wssaver.use.loadcmd:
    description: Allows specific cmds!
    default: false
  wssaver.use.delcmd:
    description: Allows specific cmds!
    default: false
commands:
  saveworld:
    usage: /saveworld <name>
    aliases: [ worldsave ]
  loadworld:
    usage: /loadworld <name>
    aliases: [ worldload ]
  deleteworld:
    usage: /deleteworld <name>
    aliases: [ delworld, worlddel, worlddelete ]